version: '3.8'
services: 
 ieee2030-client:
    build: ./IEEE-2030.5-Client
    container_name: ieee2030-client
    hostname: ieee2030-client
    environment:
      - NATS_URL=nats://nats-server:4222
      - SERVER_URL=${SERVER_URL:-https://java-backend:8443/dcap}
      - RUN_INTERVAL=${RUN_INTERVAL:-300}
      - RUN_ONCE=${RUN_ONCE:-false}
   
    networks:
      - back-nats
      - nats-mid
    command: ["${COMMAND:-all}"]

 nats-server:
    image: nats
    container_name: nats-server
    hostname: nats-server
    ports:
      - "4222:4222"
    networks:
      - nats-mid

 nats-subscriber:
   image: python:3.11
   container_name: nats-subscriber
   depends_on:
     - nats-server
   volumes:
     - ./subscriber:/app
   working_dir: /app
   command: bash -c "pip install nats-py && python publisher.py"
   #command: bash -c "pip python publisher.py"
   networks:
     - nats-mid

networks:
  back-nats:
  nats-mid: